# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azure" {
    resource_group_name  = "storage"
    storage_account_name = "tfme"
    container_name       = "tfstate"
    key                  = "win-ssh/terraform.tfstate"
  }
}
